# # This script takes in the table and builds a visualization
# takes in data generated by 07.0 script

# produces a knn visualization as a png

source('../R/model_visualization.R')

# builds a knn visualization from the classification model from figures folder
knn_visual <- knn_visualization('../figures/classification_model.csv')

# saves the knn visualization as a png in the figures folder
ggsave('../figures/classification_model_visualization.png', knn_visual)
