# Sam Thorne 
# 2023-03-10
# DSCI310 group 18 project

library(tidyverse)

# this file contains a function that joins all the separate location csv
# into one single csv used for the analysis.

#' Makes heart_data by joining place data
#' 
#' Takes in csv's generated by place_data.R and joins them into one mass csv
#' Also removes rows with 0 resting blood pressure (outliers)
#' 
#' @param place_csv is a csv read of the internet using web_data in place_data.R
#' 
#'@returns A tidy version of the data with all the correct data types
#'
#'@examples
#'# clean_csv('../data/raw/cleveland.csv')
clean_csv <- function(place_csv){
       data <- read_csv(place_csv, show_col_types = FALSE)
       if(ncol(data)>7){
       data %>%
       mutate(sex_f = as.factor(sex), 
       chest_pain_f = as.factor(chest_pain), 
       fasting_bs_f = as.factor(fasting_bs),
       rest_ECG_f = as.factor(rest_ECG), 
       exercise_f = as.factor(exercise), 
       major_vessels_f = as.factor(major_vessels), 
       thal_f = as.factor(thal), 
       diagnosis_f = as.factor(diagnosis)) %>%
       mutate(sex = as.numeric(sex), 
       chest_pain = as.numeric(chest_pain), 
       fasting_bs = as.numeric(fasting_bs),
       rest_ECG = as.numeric(rest_ECG), 
       max_heart_rate = as.numeric(max_heart_rate), 
       cholestoral_mmHg = as.numeric(cholestoral_mmHg),
       exercise = as.numeric(exercise), 
       major_vessels = as.numeric(major_vessels), 
       thal = as.numeric(thal), 
       diagnosis = as.numeric(diagnosis), 
       rest_bp = as.numeric(rest_bp))
       }else if(ncol(data) > 4){
              data %>%
              mutate(rest_bp = as.numeric(rest_bp),
       age = as.numeric(age),
       max_heart_rate = as.numeric(max_heart_rate),
       diagnosis_f = as.factor(diagnosis_f),
       sex = as.factor(sex),
       chest_pain = as.numeric(chest_pain))
       }else{
       data %>%
       mutate(diagnosis_f = as.factor(diagnosis_f))
       }
}
