# Sam Thorne 
# 2023-03-10
# DSCI310 group 18 project

# this file contains a function that joins all the separate location csv
# into one single csv used for the analysis.

#' Makes heart_data by joining place data
#' 
#' Takes in csv's generated by place_data.R and joins them into one mass csv
#' Also removes rows with 0 resting blood pressure (outliers)
#' 
#' @param hungary_csv string of relative path for hungary csv in directory
#' @param va_csv string of relative path for va csv in directory
#' @param cleveland_csv string of relative path for cleveland csv in directory
#' @param switzerland_csv string of relative path for switzerland csv in directory
#'
#'@returns csv file in './data/processed' containing every location combined.
#'
#'@examples
#'# join_csv(hungary_path, va_path, cleveland_path, switzerland_path)
join_csv <- function(hungary_csv = '../data/processed/wrangled_hungary.csv', 
                     va_csv = '../data/processed/wrangled_va.csv', 
                     cleveland_csv = '../data/processed/wrangled_cleveland.csv', 
                     switzerland_csv = '../data/processed/wrangled_switzerland.csv'){
  hungary_read <- read_csv(hungary_csv, show_col_types = FALSE)
  va_read <- read_csv(va_csv, show_col_types = FALSE)
  cleveland_read <- read_csv(cleveland_csv, show_col_types = FALSE)
  switzerland_read <- read_csv(switzerland_csv, show_col_types = FALSE)
  heart_data <- bind_rows(hungary_read, va_read, cleveland_read, switzerland_read) %>%
    slice(-157, -357, -557)
  write_csv(heart_data, '../data/processed/heart_data.csv')
  heart_data
}